### ISSUE TITLE
Exception while creating new instance of a Controller.

### ISSUE THREAD

**Issue by lenguyenthanh** [bluelinelabs/Conductor#102]
Hi @EricKuck, I'm using Conductor version `2.0.1` and randomly get this exception from Crashlytics so I'm afraid that I cannot create a sample for this. This `IntroductionPagerController` is shown when user open the app and not logged in. 
Below is code how IntroductionPagerController looks like:
```
constructor() : super()

    constructor(bundle: Bundle) : super(bundle) {
        isRegistration = bundle.getBoolean(KEY_IS_REGISTRATION)
    }

    companion object {
        private val KEY_IS_REGISTRATION = "CreateGroupController.registration"

        fun getAuthenticationInstance(): IntroductionPagerController {
            val bundle = bundle {
                putBoolean(KEY_IS_REGISTRATION, true)
            }
            return IntroductionPagerController(bundle)
        }
    }
```
And the trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.localift.localift/net.localift.localift.presentation.ui.BaseActivity}: java.lang.RuntimeException: An exception occurred while creating a new instance of net.localift.localift.presentation.ui.feature.authenticate.slide.IntroductionPagerController. null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: An exception occurred while creating a new instance of net.localift.localift.presentation.ui.feature.authenticate.slide.IntroductionPagerController. null
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:115)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.ControllerHostedRouter.restoreInstanceState(ControllerHostedRouter.java:155)
       at com.bluelinelabs.conductor.Controller.restoreInstanceState(Controller.java:981)
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:118)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.internal.LifecycleHandler.getRouter(LifecycleHandler.java:72)
       at com.bluelinelabs.conductor.Conductor.attachRouter(Conductor.java:32)
       at net.localift.localift.presentation.ui.BaseActivity.initializeRouter(BaseActivity.kt:106)
       at net.localift.localift.presentation.ui.BaseActivity.onCreate(BaseActivity.kt:57)
       at android.app.Activity.performCreate(Activity.java:5447)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:109)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.ControllerHostedRouter.restoreInstanceState(ControllerHostedRouter.java:155)
       at com.bluelinelabs.conductor.Controller.restoreInstanceState(Controller.java:981)
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:118)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.internal.LifecycleHandler.getRouter(LifecycleHandler.java:72)
       at com.bluelinelabs.conductor.Conductor.attachRouter(Conductor.java:32)
       at net.localift.localift.presentation.ui.BaseActivity.initializeRouter(BaseActivity.kt:106)
       at net.localift.localift.presentation.ui.BaseActivity.onCreate(BaseActivity.kt:57)
       at android.app.Activity.performCreate(Activity.java:5447)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter bundle
       at net.localift.localift.presentation.ui.feature.authenticate.slide.IntroductionPagerController.<init>(IntroductionPagerController.kt)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:109)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.ControllerHostedRouter.restoreInstanceState(ControllerHostedRouter.java:155)
       at com.bluelinelabs.conductor.Controller.restoreInstanceState(Controller.java:981)
       at com.bluelinelabs.conductor.Controller.newInstance(Controller.java:118)
       at com.bluelinelabs.conductor.RouterTransaction.<init>(RouterTransaction.java:33)
       at com.bluelinelabs.conductor.Backstack.restoreInstanceState(Backstack.java:114)
       at com.bluelinelabs.conductor.Router.restoreInstanceState(Router.java:452)
       at com.bluelinelabs.conductor.internal.LifecycleHandler.getRouter(LifecycleHandler.java:72)
       at com.bluelinelabs.conductor.Conductor.attachRouter(Conductor.java:32)
       at net.localift.localift.presentation.ui.BaseActivity.initializeRouter(BaseActivity.kt:106)
       at net.localift.localift.presentation.ui.BaseActivity.onCreate(BaseActivity.kt:57)
       at android.app.Activity.performCreate(Activity.java:5447)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Could you suggest me how can I fix this crash? Thanks

**Comment by adi1133** [comment]
I see no issue in the code above, try to create a simple project that isolates and reproduces the issue and post it as a separate repo. Like [this](https://github.com/search?q=user%3Aadi1133+issue).

**Comment by JakeWharton** [comment]
Change `Bundle` to `Bundle?` in the constructor parameter type declaration.

**Comment by lenguyenthanh** [comment]
@adi1133 I just update my description, because I got this crash from Crashlytics, and it works perfectly on my devices, so I'm afraid that I cannot create a sample for this.

@JakeWharton: Thanks for your suggestion. It looks reasonable. I'll try to apply it. Will report after few days.

**Comment by JakeWharton** [comment]
The exception cause clearly indicates that this is the problem. It also
should be really easy to reproduce, you just need to do something like
rotate the phone so that Conductor recreates your controllers.

**Comment by lenguyenthanh** [comment]
I tried your suggestion to reproduce the crash, but it didn't happen.

**Comment by JakeWharton** [comment]
You can just call the constructor from Java and pass `null`. This is
effectively the same thing as using reflection to look up the constructor
and invoke it with `null` which is exactly what the stacktrace indicates is
happening.

**Comment by lenguyenthanh** [comment]
Got it now, thanks.
