### ISSUE TITLE
NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found

### ISSUE THREAD

**Issue by heitorcolangelo** [bluelinelabs/Conductor#105]
Hi,
Running my app on API 16 it's crashing in the constructor:
```java
protected Controller(Bundle args) {
    this.args = args;
    instanceId = UUID.randomUUID().toString();
    ensureRequiredConstructor();
}
````
The error is thrown on line:
```java
instanceId = UUID.randomUUID().toString();
```
Does anyone already had this issue?
Thanks!

**Comment by adi1133** [comment]
Post a stacktrace

**Comment by heitorcolangelo** [comment]
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.projectname.dev/br.com.projectname.HostActivity}: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
 at android.app.ActivityThread.access$600(ActivityThread.java:130)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4745)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
 at java.security.SecureRandom.<init>(SecureRandom.java:103)
 at java.util.UUID.randomUUID(UUID.java:127)
 at com.bluelinelabs.conductor.Controller.<init>(Controller.java:136)
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:64)
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:60)
 at br.com.projectname.ui.viewcontroller.OnboardingViewController.<init>(OnboardingViewController.java:30)
 at br.com.projectname.HostActivity.onCreate(HostActivity.java:49)
 at android.app.Activity.performCreate(Activity.java:5008)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
 at android.app.ActivityThread.access$600(ActivityThread.java:130) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:137) 
 at android.app.ActivityThread.main(ActivityThread.java:4745) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:511) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
 at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
 at java.security.Provider$Service.newInstance(Provider.java:991)
 at java.security.SecureRandom.<init>(SecureRandom.java:100)
 at java.util.UUID.randomUUID(UUID.java:127) 
 at com.bluelinelabs.conductor.Controller.<init>(Controller.java:136) 
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:64) 
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:60) 
 at br.com.projectname.ui.viewcontroller.OnboardingViewController.<init>(OnboardingViewController.java:30) 
 at br.com.projectname.HostActivity.onCreate(HostActivity.java:49) 
 at android.app.Activity.performCreate(Activity.java:5008) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
 at android.app.ActivityThread.access$600(ActivityThread.java:130) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:137) 
 at android.app.ActivityThread.main(ActivityThread.java:4745) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:511) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
 at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.InstantiationException: can't instantiate class com.orhanobut.hawk.AesCbcWithIntegrity$PrngFixes$LinuxPRNGSecureRandom; no empty constructor
 at java.lang.Class.newInstanceImpl(Native Method)
 at java.lang.Class.newInstance(Class.java:1319)
 at java.security.Provider$Service.newInstance(Provider.java:989)
 at java.security.SecureRandom.<init>(SecureRandom.java:100) 
 at java.util.UUID.randomUUID(UUID.java:127) 
 at com.bluelinelabs.conductor.Controller.<init>(Controller.java:136) 
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:64) 
 at br.com.projectname.ui.viewcontroller.util.BaseViewController.<init>(BaseViewController.java:60) 
 at br.com.projectname.ui.viewcontroller.OnboardingViewController.<init>(OnboardingViewController.java:30) 
 at br.com.projectname.HostActivity.onCreate(HostActivity.java:49) 
 at android.app.Activity.performCreate(Activity.java:5008) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
 at android.app.ActivityThread.access$600(ActivityThread.java:130) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:137) 
 at android.app.ActivityThread.main(ActivityThread.java:4745) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:511) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
 at dalvik.system.NativeStart.main(Native Method)

**Comment by adi1133** [comment]
`UUID.randomUUID();` Seems to crash on your system. This is not really an issue with Conductor itself. There is a slim change that it is an issue with the device you have, but probably the issue is caused by some other code/lib your app has. Try to create a minimal project that reproduces the issue.
Some questions:
- Does calling `UUID.randomUUID()` anywhere in your current app crash it ?
- If yes, does it happen in a new android studio project? (a blank app)
- Try to create a minimal project that causes the crash, using conductor or just `UUID.randomUUID()`

**Comment by heitorcolangelo** [comment]
@adi1133 Thanks for your reply.
Turns out this crash doesn't happen on a new project. I think that maybe this is something related with hawk lib.
Feel free to close this issue, thanks again.

**Comment by adi1133** [comment]
You are welcome !
You can close your own issues on github :D
