### ISSUE TITLE
NPE from AnimationChangeHandler in version 2.0.2

### ISSUE THREAD

**Issue by krystianpe** [bluelinelabs/Conductor#136]
Haven't found any mention of this bug. I can't reproduce it but I've received crash logs from few devices. Is it fixed by any chance in 2.0.3? It's not present in 2.0.1.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.removeListener(android.animation.Animator$AnimatorListener)' on a null object reference
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:170)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.onAbortPush(AnimatorChangeHandler.java:67)
       at com.bluelinelabs.conductor.ControllerChangeHandler.abortPush(ControllerChangeHandler.java:113)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:129)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:615)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:603)
       at com.bluelinelabs.conductor.Router.popController(Router.java:121)
       at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:96)
       at com.bluelinelabs.conductor.Router.handleBack(Router.java:82)
...`
or here 
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.removeListener(android.animation.Animator$AnimatorListener)' on a null object reference
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:170)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:327)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.completeImmediately(AnimatorChangeHandler.java:77)
       at com.bluelinelabs.conductor.ControllerChangeHandler.completePushImmediately(ControllerChangeHandler.java:106)
       at com.bluelinelabs.conductor.Router.prepareForHostDetach(Router.java:484)
       at com.bluelinelabs.conductor.Router.saveInstanceState(Router.java:490)
       at com.bluelinelabs.conductor.internal.LifecycleHandler.onActivitySaveInstanceState(LifecycleHandler.java:311)
       at android.app.Application.dispatchActivitySaveInstanceState(Application.java:259)
       at android.app.Activity.onSaveInstanceState(Activity.java:1461)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:567)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
...`
or here 
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.removeListener(android.animation.Animator$AnimatorListener)' on a null object reference
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:170)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:327)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.onAbortPush(AnimatorChangeHandler.java:67)
       at com.bluelinelabs.conductor.ControllerChangeHandler.abortPush(ControllerChangeHandler.java:113)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:129)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:615)
       at com.bluelinelabs.conductor.Router.popToTransaction(Router.java:555)
       at com.bluelinelabs.conductor.Router.popToRoot(Router.java:201)
       at com.bluelinelabs.conductor.Router.popToRoot(Router.java:190)
...`

**Comment by EricKuck** [comment]
Thanks for the report. Should be fixed in the latest snapshot.

**Comment by GeoffGodwin** [comment]
Just wanted to comment that I can reproduce this with addListener and removeListener on the current version if the user locks the phone mid-orientation change. Not a super common situation but some of my users have managed to pull it off :)
