### ISSUE TITLE
ChildRouter giving me NPE

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#157]
I have a RootController (with a navigation view) that serves as a master container for the other Controllers.
My code is:

``` Java
@BindView(R.id.child_container)
FrameLayout childContainer;
private Router childRouter;

@Override
    protected void onChangeEnded(@NonNull ControllerChangeHandler changeHandler, @NonNull ControllerChangeType changeType) {
        super.onChangeEnded(changeHandler, changeType);
        if(changeType == ControllerChangeType.PUSH_ENTER){
            if(!childRouter.hasRootController())
                childRouter.setRoot(RouterTransaction.with(new FoodListController(rootComponent)).tag("Home"));
        }
    }
...
After inflateView(...)
childRouter = getChildRouter(childContainer, null);
```

If i rotate my device, I'm getting a NPE.
Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.bluelinelabs.conductor.Controller.getChildRouters()' on a null object reference
at com.bluelinelabs.conductor.ControllerHostedRouter.getSiblingRouters(ControllerHostedRouter.java:185)
at com.bluelinelabs.conductor.Router.removeAllExceptVisibleAndUnowned(Router.java:667)
at com.bluelinelabs.conductor.Router.setRoot(Router.java:260)
at com.leonardo2204.food.controller.RootController.onChangeEnded(RootController.java:92)
at com.bluelinelabs.conductor.Controller.changeEnded(Controller.java:1036)
at com.bluelinelabs.conductor.ControllerChangeHandler$1.onChangeCompleted(ControllerChangeHandler.java:174)
at com.bluelinelabs.conductor.changehandler.SimpleSwapChangeHandler.onViewAttachedToWindow(SimpleSwapChangeHandler.java:96)
at android.view.View.dispatchAttachedToWindow(View.java:13536)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1299)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by EricKuck** [comment]
Is this something that occurs every time?

**Comment by leonardo2204** [comment]
@EricKuck Yes, once I rotate my device it happens !

**Comment by EricKuck** [comment]
I haven't been able to reproduce this one. I did pretty much exactly what you said and it works great for me. Do you have a demo app or anything I could use? FWIW, that NPE you're getting should only be possible if your host controller has had its view destroyed since the last time you got the child router reference.

**Comment by leonardo2204** [comment]
I'll try posting the most important parts of the Controller:

```Java
public class RootController extends Controller {
@BindView(R.id.navigation_view)
    protected NavigationView navigationView;
    @BindView(R.id.drawer_layout)
    protected DrawerLayout drawerLayout;
    @BindView(R.id.toolbar)
    Toolbar toolbar;
    @BindView(R.id.child_container)
    FrameLayout childContainer;

    @Inject
    ActionBarOwner actionBarOwner;
    @BindDrawable(R.drawable.ic_menu)
    Drawable ic_menu;

    private int menuItemId;
    private Router childRouter;
    private Subscription navigationMenuSubscription;
    private RootComponent rootComponent;

    public RootController() {
        setHasOptionsMenu(true);
    }

    public RootComponent getRootComponent() {
        return rootComponent;
    }

    @Override
    protected void onCreate() {
        super.onCreate();
        rootComponent = DaggerRootComponent.builder()
                .exposedComponent(((HomeChefApplication)getApplicationContext()).getExposedComponent())
                .rootModule(new RootModule())
                .build();

        rootComponent.inject(this);
    }

    @Override
    protected void onChangeEnded(@NonNull ControllerChangeHandler changeHandler, @NonNull ControllerChangeType changeType) {
        super.onChangeEnded(changeHandler, changeType);
        if(changeType == ControllerChangeType.PUSH_ENTER){
            if(!childRouter.hasRootController())
                childRouter.setRoot(RouterTransaction.with(new FoodListController(rootComponent)).tag("Home"));
        }
    }

    @NonNull
    @Override
    protected View inflateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        return inflater.inflate(R.layout.controller_root, container, false);
    }

    @Override
    protected void onViewCreated(@NonNull View view) {
        setupUI();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                drawerLayout.openDrawer(navigationView);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    private void setupNavigationView() {
        View headerView = navigationView.getHeaderView(0);
        ImageView profileImage = (ImageView) headerView.findViewById(R.id.navigation_profile_pic);
        TextView profileName = (TextView) headerView.findViewById(R.id.navigation_profile_name);
        TextView profileEmail = (TextView) headerView.findViewById(R.id.navigation_profile_email);

        headerView.setOnClickListener(view -> {
            openProfile();
            drawerLayout.closeDrawer(navigationView);
        });


        Glide.with(getActivity()).load(user.getPhotoUrl()).into(profileImage);
        profileName.setText(user.getDisplayName());
        profileEmail.setText(user.getEmail());
    }

    private void openProfile() {
        getRouter()
                .pushController(RouterTransaction
                        .with(new ProfileController(user.getUid(), getRootComponent()))
                        .pushChangeHandler(new FadeChangeHandler())
                        .popChangeHandler(new FadeChangeHandler()));
    }

    private void setupUI() {
        ((AppCompatActivity) getActivity()).setSupportActionBar(toolbar);
        actionBarOwner.setActionBarCallbacks(this);
        actionBarOwner.setConfig(new ActionBarOwner.Config(true, true, ic_menu, "Delicias"));

        setupNavigationView();


        childRouter = getChildRouter(childContainer, null);
        navigationMenuSubscription = RxNavigationView.itemSelections(navigationView)
                .subscribe(menuItem -> {

                    if (menuItemId == menuItem.getItemId()) {
                        drawerLayout.closeDrawer(navigationView);
                    }

                    final Controller destination;
                    String tag;

                    switch (menuItem.getItemId()) {
                        case R.id.menu_main_logout:
                            FirebaseAuth.getInstance().signOut();
                            break;
                        case R.id.menu_main_profile:
                            openProfile();
                            drawerLayout.closeDrawer(navigationView);
                            break;
                        case R.id.menu_main_home:
                            changeController(new FoodListController(rootComponent), "Home");
                            break;
                    }
//                    case R.id.menu_entries:
//                        tag = "HOME";
//                        destination = new HomeController(RootController.this);
//                        break;
//                    case R.id.menu_drafts:
//                        tag = "DRAFT";
//                        destination = new DraftController(RootController.this);
//                        break;
//                    default:
//                        tag = "HOME";
//                        destination = new HomeController(RootController.this);
//                        break;
//                }

                    drawerLayout.closeDrawer(navigationView);
                    menuItem.setChecked(true);
                    menuItemId = menuItem.getItemId();
                });
    }

    @Override
    public boolean handleBack() {
        if(childRouter.getBackstackSize() > 0)
            return getRouter().popCurrentController();
        else
            return super.handleBack();
    }

    private void changeController(Controller controller, String tag) {
        if (childRouter.getControllerWithTag(tag) == null)
            childRouter.pushController(RouterTransaction.with(controller).tag(tag));
        else
            childRouter.popToTag(tag);

        drawerLayout.closeDrawer(navigationView);
    }
```

Thanks for the quick reply !

**Comment by EricKuck** [comment]
What calls `onViewCreated`? I assume there's some base class?

**Comment by leonardo2204** [comment]
Sorry about that, I forgot to add it:

```Java
public abstract class BaseController extends RxController {

    private boolean created;

    public BaseController() {
    }

    public BaseController(Bundle args) {
        super(args);
    }

    @NonNull
    protected abstract View inflateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container);

    @NonNull
    @Override
    protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        if(!created) {
            created = true;
            onCreate();
        }

        View view = inflateView(inflater, container);
        ButterKnife.bind(this, view);
        onViewCreated(view);

        return view;
    }

    protected void onCreate(){}
    protected void onViewCreated(@NonNull View view){}
}
```

**Comment by EricKuck** [comment]
Which version of conductor are you using? I have a very similar setup and haven't had issues. I also tried to reproduce what you had and didn't get any crashes.

Also, you can unbind the view in `onDestroyView`: https://github.com/bluelinelabs/Conductor/blob/develop/demo/src/main/java/com/bluelinelabs/conductor/demo/controllers/base/ButterKnifeController.java

**Comment by leonardo2204** [comment]
Hmm that's awkward, where else should I double check ?
I'm using version 2.0.3
Thanks for the feedback !

**Comment by EricKuck** [comment]
Yeah, I'm not sure. I just tried everything you posted on 2.0.3 and am not getting any crashes. Any chance you could post a demo app of some kind?

**Comment by leonardo2204** [comment]
I was thinking which approach would be the best to come up with an example, but I think I've narrowed down what the mistake might be.
Actually, my RootController inherits a BaseAuthController:

```Java
public abstract class BaseAuthController extends BaseController {

    private FirebaseAuth.AuthStateListener authStateListener;
    private FirebaseAuth auth = FirebaseAuth.getInstance();

    @Override
    protected void onAttach(@NonNull View view) {
        super.onAttach(view);
        setupListener();
        auth.addAuthStateListener(authStateListener);
    }

    private void setupListener() {
        authStateListener = firebaseAuth -> {
            Timber.d("RootControl - %s", "entered BaseAuthController");
            if(firebaseAuth.getCurrentUser() == null && getRouter().getControllerWithTag("Login") == null){
                Timber.d("RootControl - %s", "set root LoginBase from FB callback");
                // if(!sharedPreferences.getBoolean("WELCOME_SEEN", false))
                //   parentRouter.setRoot(RouterTransaction.with(new WelcomeController()));
                //else
                getRouter().setRoot(RouterTransaction.with(new LoginBaseController()).tag("Login"));
            }else if(firebaseAuth.getCurrentUser() != null && getRouter().getControllerWithTag("Main") == null){
                Timber.d("RootControl - %s", "set root RootController from FB callback");
                getRouter().setRoot(RouterTransaction.with(new RootController()).tag("Main")
                        .pushChangeHandler(new FadeChangeHandler(600)));
            }
        };
    }

    @Override
    protected void onDetach(@NonNull View view) {
        super.onDetach(view);
        auth.removeAuthStateListener(authStateListener);
        authStateListener = null;
    }
}
```
And I'm getting the following sequence of events:
Before rotation:
```
11-10 22:50:07.527 25679-25679/com.leonardo2204.food D/MainActivity: RootControl -attach router activity
11-10 22:50:07.527 25679-25679/com.leonardo2204.food D/MainActivity: RootControl -set root RootController from activity
11-10 22:50:07.720 25679-25679/com.leonardo2204.food D/RootController: RootControl - assigning childRouter rootController
11-10 22:50:07.835 25679-25679/com.leonardo2204.food D/RootController: RootControl - set root FoodListController from RootChangeEnded
11-10 22:50:08.086 25679-25679/com.leonardo2204.food D/BaseAuthController: RootControl - entered BaseAuthController
```
After rotation:
```
11-10 22:51:17.172 25679-25679/com.leonardo2204.food D/RootController: RootControl - destroying rootController
11-10 22:51:17.225 25679-25679/com.leonardo2204.food D/RootController: RootControl - assigning childRouter rootController
11-10 22:51:17.228 25679-25679/com.leonardo2204.food D/MainActivity: RootControl -attach router activity
11-10 22:51:17.229 25679-25679/com.leonardo2204.food D/MainActivity: RootControl -set root RootController from activity
11-10 22:51:17.229 25679-25679/com.leonardo2204.food D/RootController: RootControl - destroying rootController
11-10 22:51:17.232 25679-25679/com.leonardo2204.food D/RootController: RootControl - assigning childRouter rootController
11-10 22:51:17.279 25679-25679/com.leonardo2204.food D/RootController: RootControl - set root FoodListController from RootChangeEnded
```
And the crash happens right after the last log event.
I'm suspecting it might be happening because of the async behavior from Firebase...

P.S: My MainActivity:
```Java
public class MainActivity extends AppCompatActivity {

    @BindView(R.id.parent_container)
    ViewGroup parentContainer;

    private Router parentRouter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        ((HomeChefApplication)getApplicationContext()).getExposedComponent().inject(this);

        parentRouter = Conductor.attachRouter(this, parentContainer, savedInstanceState);
        Timber.d("RootControl -%s", "attach router activity");

        if(FirebaseAuth.getInstance().getCurrentUser() != null) {
            Timber.d("RootControl -%s", "set root RootController from activity");
            parentRouter.setRoot(RouterTransaction.with(new RootController()).tag("Main"));
        }else {
            Timber.d("RootControl -%s", "set root LoginBaseController from activity");
            parentRouter.setRoot(RouterTransaction.with(new LoginBaseController()).tag("Login"));
        }
    }
}
```

**Comment by leonardo2204** [comment]
I think I solved it !

Adding the `!parentRouter.hasRootController()` in my activity onCreate did it !

So: 
```Java
if(FirebaseAuth.getInstance().getCurrentUser() != null && !parentRouter.hasRootController()) {
            Timber.d("RootControl -%s", "set root RootController from activity");
            parentRouter.setRoot(RouterTransaction.with(new RootController()).tag("Main"));
        }else if(!parentRouter.hasRootController()) {
            Timber.d("RootControl -%s", "set root LoginBaseController from activity");
            parentRouter.setRoot(RouterTransaction.with(new LoginBaseController()).tag("Login"));
        }
```

Two questions @EricKuck before I close the issue:
1st - Is this a good approach to handle this kind of situation ? I mean, the async and listener stuff ?? (Setting the root Router as the Root classes depending on the listener callback ?)
2nd - I was getting this weird behavior because a new parentRouter root was being created (on MainActivity), thus all it's children were destroyed along with their histories, am I right here ?

Again, thank you so much for your time and all the effort and help !

**Comment by EricKuck** [comment]
Ah, that makes sense now. Since you weren't initially doing the `!parentRouter.hasRootController()` check, you ended up destroying the root controller that was already there. When the async task that was happening on that now-destroyed controller returned, it tried to access its router, which was now null.

I'd suggest putting an `if (!isDestroyed())` check in your listener, since that will potentially be called after your controller's been destroyed. Even better - somehow cancel the call you made on the destroy event. I haven't done much with Firebase yet, so I'm not sure if that's an option or not.

I'll add a few checks to calls like this that will throw `IllegalStateException`s so things are a bit clearer next time.

**Comment by leonardo2204** [comment]
Thank you so much for clarifying that matter, so I guess my point was right about the rootController.
By attaching (setting the listener) and detaching (removing the listener) wouldn't do the job, instead of `!isDestroyed()` ? Or they are not mutually exclusive ?

Thanks again !

**Comment by EricKuck** [comment]
Yep, removing the listener when the controller is detached would do the job too. I just don't know enough about Firebase to say what's possible and what isn't.

**Comment by leonardo2204** [comment]
Ok then, I'll keep that in mind !
Thank you again for the help man !
