### ISSUE TITLE
ControllerPagerAdapter/ViewPager no longer working

### ISSUE THREAD

**Issue by AranHase** [bluelinelabs/Conductor#160]
I'm using version 2.0.4-SNAPSHOT, and a recent updated is causing NPE on my ViewPagers. Here is the stacktrace:

```
11-10 00:22:33.157 13524-13524/com.bluelinelabs.conductor.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.bluelinelabs.conductor.demo, PID: 13524
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'com.bluelinelabs.conductor.Router com.bluelinelabs.conductor.Controller.getRouter()' on a null object reference
                                                                                     at com.bluelinelabs.conductor.support.ControllerPagerAdapter.destroyItem(ControllerPagerAdapter.java:64)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1074)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                                     at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I haven't looked too much into it yet, but I noticed the method `ControllerPagerAdapter::getItem(position: Int)` is not being called for some positions. For example, on the demo app, it is called for position 0 (more than one time), and when I swipe to the right twice, it is called for position 3, skipping 1, and 2.

Then it crashes, maybe because it will try to destroy the controller on position 1, but fails because it was never created.

## Steps to reproduce

1. Start the demo app
2. Choose `ViewPager`
3. Swipe to the right
4. Swipe to the left*

\* If I swipe only to the right, it will give a slight different crash, but same NPE problem.

**Comment by AranHase** [comment]
Did some more debugging today and it looks like the change below is responsible for this issue:

https://github.com/bluelinelabs/Conductor/commit/977db6b5bf9dabe31bf146ebbd4e76e572f5d72f#diff-ebd2530251da1d69071be051f7a91219L43

When this change is reverted, it works again.


Looks like the problem arose because the same container is used for all the pages, and, without tagging the "child routers", a single router is used for all the pages. Therefore, the conditional below `!router.hasRootController()`* will result in true only for the first page and ignore the rest, thus returning "null" controllers.

Maybe this is a valid use case for `getChildRouter(ViewGroup,String)`? Relevant to #155 ?

\* [link](https://github.com/bluelinelabs/Conductor/blob/977db6b5bf9dabe31bf146ebbd4e76e572f5d72f/conductor-support/src/main/java/com/bluelinelabs/conductor/support/ControllerPagerAdapter.java#L52)

**Comment by EricKuck** [comment]
Great find! I was pretty sure the tag parameter was left there for a reason, but I could not remember what it was. This was documented very poorly, which I'm in the process of fixing now. Thanks!
