### ISSUE TITLE
Using MapView with Conductor

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#170]
So, I'm trying to use the great lib [MapView](https://github.com/airbnb/AirMapView) from Airbnb along with Conductor, but with no luck.
Whenever I "start" my MapController, I'm getting the following error:

```
java.lang.IllegalArgumentException: No view found for id 0x7f0e00b3 (com.leonardo2204.food:id/address_dialog_map) for fragment NativeGoogleMapFragment{19d2c737 #1 id=0x7f0e00b3}
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:594)
    at com.airbnb.android.airmapview.AirMapView.initialize(AirMapView.java:76)
    at com.airbnb.android.airmapview.AirMapView.initialize(AirMapView.java:91)
    at com.leonardo2204.food.address_pick.AddressPickController.onViewCreated(AddressPickController.java:32)
    at com.leonardo2204.food.controller.base.BaseController.onCreateView(BaseController.java:43)
    at com.bluelinelabs.conductor.Controller.inflate(Controller.java:823)
    at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:151)
    at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:632)
    at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:620)
    at com.bluelinelabs.conductor.Router.pushController(Router.java:140)
    at com.leonardo2204.food.food_list.FoodListController.onChangeAddressPickClick(FoodListController.java:122)
    at com.leonardo2204.food.food_list.FoodListController_ViewBinding$1.doClick(FoodListController_ViewBinding.java:31)
    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
    at android.view.View.performClick(View.java:4780)
    at android.view.View$PerformClick.run(View.java:19866)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
I have it implemented like this:

```Java
public class AddressPickController extends BaseController {

    @BindView(R.id.address_dialog_map)
    AirMapView mapView;

    @NonNull
    @Override
    protected View inflateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        return inflater.inflate(R.layout.controller_address, container, false);
    }

    @Override
    protected void onViewCreated(@NonNull View view) {
        mapView.initialize(((AppCompatActivity)getActivity()).getSupportFragmentManager());
    }
}
```
Where `onViewCreated` is simply called after layout inflation and Butterknife binding.
The xml has just the `AirMapView` inside a FrameLayout.

I suspect there is nothing I can do to make them both work, since Airbnb lib uses Fragments to take care of the maps lifecycles etc, am I correct here or is there a way to do so ?

Thanks

**Comment by EricKuck** [comment]
Do you have any updates on this? I just tried using AirMapView for the first time and it worked right off the bat. There shouldn't be any interop issues with support fragments that would cause exceptions like this.

**Comment by leonardo2204** [comment]
Thanks for the reply ! Did you try as I did in the examples above ? I tried using Google Maps.
Thanks

**Comment by EricKuck** [comment]
Other than resource id and not using Butterknife, my code was pretty much identical to yours. I also used Google Maps. I just used the home controller in a demo app, so there wasn't anything special about my setup at all.

I looked through the code for `FragmentManagerImpl` a bit and think I know why it's crashing for you though (and now I have no idea why it works for me). The line that throws that exception tries to find the containing view via `(ViewGroup)mActivity.findViewById(fragment.mContainerId)`. The way you have it setup, AirMapView is being initialized in `onCreateView`, where it hasn't yet been added to the host container, and therefore isn't anywhere that the `FragmentManager` could access it. Can you try delaying this call until the controller's view has been added? The easiest way to do this would be to make this call in `onChangeStarted`, but you could also use an `OnAttachStateChangeListener` to accomplish this.

**Comment by leonardo2204** [comment]
Sorry for the delay, I'll give it a try to see how it goes !
Thanks for looking into it 👍

**Comment by EricKuck** [comment]
I'll assume this is working as expected now. If you're still having issues, feel free to reopen.

**Comment by markus2610** [comment]
@leonardo2204 Does it work with you? I also get the exception.

**Comment by leonardo2204** [comment]
@markus2610 sorry for the long delay, I'm back programming server side, so I haven't had time to go through some Android stuff.
Sorry about that

**Comment by markus2610** [comment]
So works

` override fun onChangeEnded(changeHandler: ControllerChangeHandler,
      changeType: ControllerChangeType) {
    super.onChangeEnded(changeHandler, changeType)

    if(changeType.isEnter) {
      mapView.setOnMapInitializedListener(this)
      mapView.initialize((activity as AppCompatActivity).supportFragmentManager)
    }
  }`
