### ISSUE TITLE
NullPointerException when calling getActivity() in onDestroy()

### ISSUE THREAD

**Issue by chip2n** [bluelinelabs/Conductor#203]
Calling `getActivity()` inside `onDestroy()` seems to cause a NullPointerException in some cases. This happens for me in particular when opening the app from a deep link while the app is running.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.test.app, PID: 17311
                  java.lang.RuntimeException: Unable to destroy activity {com.test.app/com.test.app.main.presentation.view.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.bluelinelabs.conductor.Router.getActivity()' on a null object reference
                      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
                      at android.app.ActivityThread.-wrap5(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity com.bluelinelabs.conductor.Router.getActivity()' on a null object reference
                      at com.bluelinelabs.conductor.Controller.getActivity(Controller.java:270)
                      at com.test.app.ui.BaseController.onDestroy(BaseController.kt:125)
                      at com.bluelinelabs.conductor.Controller.performDestroy(Controller.java:948)
                      at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:868)
                      at com.bluelinelabs.conductor.Controller.destroy(Controller.java:975)
                      at com.bluelinelabs.conductor.Controller.destroy(Controller.java:960)
                      at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:61)
                      at com.bluelinelabs.conductor.Backstack.popAll(Backstack.java:82)
                      at com.bluelinelabs.conductor.Router.destroy(Router.java:190)
                      at com.bluelinelabs.conductor.ControllerHostedRouter.destroy(ControllerHostedRouter.java:77)
                      at com.bluelinelabs.conductor.Controller.destroy(Controller.java:971)
                      at com.bluelinelabs.conductor.Controller.activityDestroyed(Controller.java:771)
                      at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:492)
                      at com.bluelinelabs.conductor.ActivityHostedRouter.onActivityDestroyed(ActivityHostedRouter.java:41)
                      at com.bluelinelabs.conductor.internal.LifecycleHandler.destroyRouters(LifecycleHandler.java:194)
                      at com.bluelinelabs.conductor.internal.LifecycleHandler.onDestroy(LifecycleHandler.java:149)
                      at android.app.Fragment.performDestroy(Fragment.java:2433)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1098)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
                      at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1981)
                      at android.app.FragmentController.dispatchDestroy(FragmentController.java:218)
                      at android.app.Activity.performDestroy(Activity.java:6406)
                      at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
                      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
                      at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

The reason for the exception seems to be that the router is null when `onDestroy()` is called. It might be a good idea to check for a null router before attempting to call `router.getActivity()` to avoid such crashes. If that seems to be a desirable solution, I'd be happy to create a pull request for it.

In case it's relevant, the use case in my case is monitoring memory leaks using LeakCanary in the following way (in Kotlin):

```
override fun onDestroy() {
    super.onDestroy()
    if (activity != null) {
        BaseContext.getRefWatcher(activity!!).watch(this)
    }
}
```

**Comment by EricKuck** [comment]
Thanks! This is now fixed in the latest snapshot and will be getting pushed to a proper release within the next hour or so.
