### ISSUE TITLE
NPE: unregisterAttachListener

### ISSUE THREAD

**Issue by PaulWoitaschek** [bluelinelabs/Conductor#348]
When calling `Router.popController` in `postCreateView`, conductor crashes with a NPE.

```kotlin
class MainActivity : Activity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val viewGroup = findViewById(android.R.id.content) as ViewGroup
    val router = Conductor.attachRouter(this, viewGroup, savedInstanceState)
    if (!router.hasRootController()) {
      router.pushController(RouterTransaction.with(PopInPostCreateView()))
    }
  }

  class PopInPostCreateView : Controller() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View = View(activity!!)

    init {
      addLifecycleListener(object : LifecycleListener() {
        override fun postCreateView(controller: Controller, view: View) {
          router.popController(this@PopInPostCreateView)
        }
      })
    }
  }
}
```

```
E: FATAL EXCEPTION: main
   Process: de.paul_woitaschek.condutordialogtest, PID: 22296
   java.lang.RuntimeException: Unable to start activity ComponentInfo{de.paul_woitaschek.condutordialogtest/de.paul_woitaschek.condutordialogtest.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.ViewAttachHandler.unregisterAttachListener(android.view.View)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
       at android.app.ActivityThread.-wrap11(Unknown Source:0)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.ViewAttachHandler.unregisterAttachListener(android.view.View)' on a null object reference
       at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:952)
       at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1097)
       at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1082)
       at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:61)
       at com.bluelinelabs.conductor.Router.popController(Router.java:135)
       at de.paul_woitaschek.condutordialogtest.MainActivity$PopInPostCreateView$1.postCreateView(MainActivity.kt:32)
       at com.bluelinelabs.conductor.Controller.inflate(Controller.java:995)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:726)
       at com.bluelinelabs.conductor.Router.pushController(Router.java:179)
       at de.paul_woitaschek.condutordialogtest.MainActivity.onCreate(MainActivity.kt:20)
       at android.app.Activity.performCreate(Activity.java:6975)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
       at android.os.Handler.dispatchMessage(Handler.java:105) 
       at android.os.Looper.loop(Looper.java:164) 
       at android.app.ActivityThread.main(ActivityThread.java:6541) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

```

**Comment by tomblenz** [comment]
Same here.
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.ViewAttachHandler.unregisterAttachListener(android.view.View)' on a null object reference
        at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:976)
        at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1121)
        at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1106)
        at com.bluelinelabs.conductor.Router.setBackstack(Router.java:493)
        at com.bluelinelabs.conductor.Router.setRoot(Router.java:336)
// code that sets root here
        at com.my.ControllerLifecycleOwner$1.postCreateView(SourceFile:19)
        at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1019)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
        at com.bluelinelabs.conductor.Router.setBackstack(Router.java:456)
        at com.bluelinelabs.conductor.Router.setRoot(Router.java:336)
        at com.my.MainActivity.onCreate(MainActivity.kt:83)
        at android.app.Activity.performCreate(Activity.java:6221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723) 
        at android.app.ActivityThread.access$900(ActivityThread.java:172) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5832) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```

**Comment by vincent-paing** [comment]
Have you found solution to this?
