### ISSUE TITLE
Context in `PreContextUnavailable` callback is null, breaking kotlin intrinsic null check

### ISSUE THREAD

**Issue by yousuf-haque** [bluelinelabs/Conductor#377]
I've gotten several crashlytics reports of a kotlin null pointer exception ocurring in the following block of code. In the documentation, and the source, the context passed in during `preContextUnavailable` should be `@NonNull`, however I received the crash that I've listed below.

Any insight into what I'm doing wrong? Or why context is null?

I've created an extension function on controller, that creates a stream of a controller's lifecycle events. Below is the sample code.

Thanks for the help!

```kotlin
fun Controller.lifecycleStream(): Observable<ControllerLifecycleEvent> =
        Observable.create({ emitter: Emitter<ControllerLifecycleEvent> ->
                    emitter.onNext(getCurrentLifecycleStatus())

                    addLifecycleListener(object : Controller.LifecycleListener() {

                        //other lifecycle callbacks...

                        // context seems to be null here
                        override fun preContextUnavailable(controller: Controller, context: Context ) {
                    emitter.onNext(ControllerLifecycleEvent.PreContextUnavailable(controller, context))
                        }

                        //other lifecycle callbacks...
                     
                    })
        }, Emitter.BackpressureMode.BUFFER)
```
```kotlin
fun Controller.getCurrentLifecycleStatus(): ControllerLifecycleEvent =
        when {
            isDestroyed -> ControllerLifecycleEvent.PostDestroy(this)
            isBeingDestroyed -> ControllerLifecycleEvent.PreDestroy(this)
            isAttached -> ControllerLifecycleEvent.PostAttach(this, view!!)
            view != null -> ControllerLifecycleEvent.PostCreateView(this, view!!)
            activity != null -> ControllerLifecycleEvent.PostContextAvailable(this, activity!!)
            else -> ControllerLifecycleEvent.Create
        }
```

```kotlin
sealed class ControllerLifecycleEvent {
    // other lifecycle events

    data class PreContextUnavailable(val controller: Controller, val context: Context) : ControllerLifecycleEvent()

    // other lifecycle events
}
```

```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context
       at some.package.name.ConductorExtensionsKt$lifecycleStream$1$1.preContextUnavailable(ConductorExtensions.kt)
       at com.bluelinelabs.conductor.Controller.performDestroy(Controller.java:1050)
       at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:972)
       at com.bluelinelabs.conductor.Controller.detach(Controller.java:935)
       at com.bluelinelabs.conductor.Controller$7.onDetached(Controller.java:1014)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportDetached(ViewAttachHandler.java:103)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.onViewDetachedFromWindow(ViewAttachHandler.java:58)
       at android.view.View.dispatchDetachedFromWindow(View.java:15593)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3190)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3182)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3277)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5935)
       at android.view.ViewRootImpl.die(ViewRootImpl.java:5912)
       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4284)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4536)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by yousuf-haque** [comment]
Sorry to ping, but we have some prod crashes due to this, and I just want to know if I'm doing something incorrectly. Any Ideas? @EricKuck 

Upon further digging, I realized that within my main controller, I check a condition within onAttach, and conditionally launch another activity, and finish the current one. Could it be that because I'm finishing the current activity, and launching a new one, the async nature of finish is causing this null pointer exception?

Thanks
