### ISSUE TITLE
java.lang.NullPointerException in Controller::attach.

### ISSUE THREAD

**Issue by fvink** [bluelinelabs/Conductor#407]
I got this crash in Crashlytics so unfortunately I don't have the steps to reproduce the issue.
Device: Lenovo Tab4 10
OS: Android 7.1.1

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
       at com.bluelinelabs.conductor.Controller.attach(Controller.java:879)
       at com.bluelinelabs.conductor.Controller.access$500(Controller.java:44)
       at com.bluelinelabs.conductor.Controller$7.onAttached(Controller.java:1005)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached(ViewAttachHandler.java:87)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.access$100(ViewAttachHandler.java:7)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached(ViewAttachHandler.java:47)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow(ViewAttachHandler.java:126)
       at android.view.View.dispatchAttachedToWindow(View.java:15524)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by DSteve595** [comment]
In our case, this was caused by our custom change handler overriding `removesViewOnPush()` to return false. Fixed that up and the crash disappeared.

**Comment by MkhytarMkhoian** [comment]
@DSteve595 It's a bad solution because your view left in the container and it causes memory leaks and extra overdraw

**Comment by DSteve595** [comment]
@Mkhytar Right, we were originally doing that (returning `false`), and changing it to `true` fixed it.
