### ISSUE TITLE
When using ChildRouter and RETAIN_DETACH, NPE happens

### ISSUE THREAD

**Issue by szantogab** [bluelinelabs/Conductor#424]
Hi!

I have a main controller in my application, which has a bottom tab bar. Each tab has its own child router, each wrapped in separate FrameLayout. This way I can show / hide the FrameLayouts (tabs) without having to reload all tab controllers.

The problem arises when I push a controller on the main controller, and would like to return back to the main controller. I am using RETAIN_DETACH on all controllers, because recreating the whole view hierarchy would be expensive, and would cause lag.

If I don't use child routers (don't call the `getChildRouter(viewGroup)`), or I don't set `retainViewMode = RetainViewMode.RETAIN_DETACH`, the problem disappears.

This is the exception I get:

```java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
                                                                         at com.bluelinelabs.conductor.Controller.attach(Controller.java:879)
                                                                         at com.bluelinelabs.conductor.Controller.access$500(Controller.java:44)
                                                                         at com.bluelinelabs.conductor.Controller$7.onAttached(Controller.java:1005)
                                                                         at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached(ViewAttachHandler.java:87)
                                                                         at com.bluelinelabs.conductor.internal.ViewAttachHandler.access$100(ViewAttachHandler.java:7)
                                                                         at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached(ViewAttachHandler.java:47)
                                                                         at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow(ViewAttachHandler.java:126)
                                                                         at android.view.View.dispatchAttachedToWindow(View.java:17456)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                                                                         at android.view.ViewGroup.addViewInner(ViewGroup.java:4977)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4768)
                                                                         at android.view.ViewGroup.addView(ViewGroup.java:4708)
                                                                         at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.performChange(AnimatorChangeHandler.java:128)
                                                                         at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:204)
                                                                         at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
                                                                         at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
                                                                         at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
                                                                         at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:726)
                                                                         at com.bluelinelabs.conductor.Router.popController(Router.java:136)
                                                                         at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:118)
                                                                         at com.bluelinelabs.conductor.Router.handleBack(Router.java:96)
                                                                         at com.bluelinelabs.conductor.Controller.handleBack(Controller.java:613)
                                                                         at com.bluelinelabs.conductor.Router.handleBack(Router.java:94)
                                                                         at com.apptive.parashout.MainActivity.onBackPressed(MainActivity.kt:50)
```

Any idea what could go wrong here? Is this a library bug?

**Comment by dimsuz** [comment]
Your excepiton presented above misses a first line which is actually rather important as it specifies the actual exception which occurred

**Comment by szantogab** [comment]
Sorry, here is the first line:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference

**Comment by szantogab** [comment]
@dimsuz Do you have any idea what can be the problem here? I'm stuck. :(

**Comment by szantogab** [comment]
Solved the problem by setting 
`(RouterTransaction.with(controller).pushChangeHandler(HorizontalChangeHandler(false)).popChangeHandler(HorizontalChangeHandler(false)))`, so when the new controller is pushed the previous controller's view is not removed.

**Comment by bishwajeetbiswas** [comment]
> Solved the problem by setting
> `(RouterTransaction.with(controller).pushChangeHandler(HorizontalChangeHandler(false)).popChangeHandler(HorizontalChangeHandler(false)))`, so when the new controller is pushed the previous controller's view is not removed.

It solved my crash
