### ISSUE TITLE
performControllerChange - "Trying to push a controller that's already been destroyed"

### ISSUE THREAD

**Issue by atrang89** [bluelinelabs/Conductor#445]
First off, HAZAH to the great Erick coming back.  The last pull request was Oct 2017?  Seeing new pull request is showing signs of life again.  Thanks for this library.

There might be a deep bug in ViewPager when starting another activity.  Getting the message error PerformControllerChange in conductor.  "Trying to push a controller that's already been destroyed".  I think its the first activity being destroyed.

**Comment by PaulWoitaschek** [comment]
Can you provide a sample project that demonstrates your bug?

**Comment by atrang89** [comment]
Sorry Paul, I wish I could but this has some propriety code which may take a long time to remove them all.  I might try and get something out for you guys.  But are you familiar with that message and how I may be able to avoid it?

**Comment by PaulWoitaschek** [comment]
Nothing obvious. Besides not doing what the error message says ;)

Can you post the stack trace?

**Comment by atrang89** [comment]
I'm a newer developer, and I'd like to thank you personally for looking into this.  Even if we can't solve this, any leads will help me understand this a little better.  Here's the stacktrace.

Fatal Exception: java.lang.IllegalStateException: Trying to push a controller that has already been destroyed. (aw)
       at com.bluelinelabs.conductor.h.a(Unknown Source:45)
       at com.bluelinelabs.conductor.h.a(Unknown Source:26)
       at com.bluelinelabs.conductor.h.a(Unknown Source:141)
       at com.bluelinelabs.conductor.g.a(Unknown Source:27)
       at com.bluelinelabs.conductor.h.d(Unknown Source:11)
       at com.bluelinelabs.conductor.support.ControllerPagerAdapter.instantiateItem(Unknown Source:59)
       at android.support.v4.view.ViewPager.a(Unknown Source:9)
       at android.support.v4.view.ViewPager.a(Unknown Source:252)
       at android.support.v4.view.ViewPager.c(Unknown Source:2)
       at android.support.v4.view.ViewPager.onMeasure(Unknown Source:207)
       at android.view.View.measure(View.java:22071)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(Unknown Source)
       at android.support.design.widget.n.a(Unknown Source:82)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.a(Unknown Source)
       at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source:246)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source:125)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
       at android.view.View.measure(View.java:22071)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by PaulWoitaschek** [comment]
That's obfuscated. Can you reproduce the crash yourself? If so please post a stacktrace when running in debug build.

**Comment by atrang89** [comment]
Im going to close this ticket until I can get you the stace trace.  For some reason its not crashing.  An additional note, i believe this has something to do with Android 8.0 update.  Now that my devices are on 8.1 i'm rarely seeing this.
