### ISSUE TITLE
"Trying to push a controller that has already been destroyed" - Conductor Message

### ISSUE THREAD

**Issue by atrang89** [bluelinelabs/Conductor#446]
Found the stacktrace, the message "Trying to push a controller that has already been destroyed"  is coming directly from the conductor library.  Occurs when starting a new activity (in this case opening a third party library camera).

--------- beginning of crash
06-15 15:53:36.341 12826-12826/com.michiganfirst.mb.client.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.michiganfirst.mb.client.debug, PID: 12826
    java.lang.IllegalStateException: Trying to push a controller that has already been destroyed. (DepositView)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:753)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
        at com.bluelinelabs.conductor.Router.setBackstack(Router.java:430)
        at com.bluelinelabs.conductor.ControllerHostedRouter.setBackstack(ControllerHostedRouter.java:106)
        at com.bluelinelabs.conductor.Router.setRoot(Router.java:333)
        at com.bluelinelabs.conductor.support.ControllerPagerAdapter.instantiateItem(ControllerPagerAdapter.java:65)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1182)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
        at android.view.View.measure(View.java:22071)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
06-15 15:53:36.342 12826-12826/com.michiganfirst.mb.client.debug E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by EricKuck** [comment]
`ControllerPagerAdapter` is deprecated. Can you move over to `RouterPagerAdapter` and see if the issue still exists? This just involves changing a few lines. From what I can tell, this issue does not exist in the new class.

**Comment by atrang89** [comment]
I will close this in a couple days, been testing and seems to give me actual errors instead of the previous one.  Thanks a lot for this, been wrapping my head around it for days.  

On another note, using intents to start activity and onActivityResult callback works great but works oddly with Toast Message.  Doesn't even let buttons become tappable anymore.  This is not an issue for me, but a heads up.
