### ISSUE TITLE
View NPE in Controller's onAttach() method

### ISSUE THREAD

**Issue by Gaket** [bluelinelabs/Conductor#498]
Hi!

Recently we ran into an issue, where we get a View NPE in the Controller's onAttach method. Not always, these reports came from Crashlytics. We use a `ButterKnifeController` as its parent, so the view is definitely bound in `onCreateView` method. Unbinding happens only in `onDestroyView`, as usual.

The expectation is to always have bound views in onAttach() method, but for some reasons it is not the case.

Does somebody have any clues what can go wrong here? We were not able to reproduce the issue. If there is some additional info required - please, let me know.

 ```
 @BindView(R2.id.thumbnailView)
  ImageView thumbnailView;
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setBackgroundResource(int)' on a null object reference
       at com.vyng.dialer_ui.call_screen.CallScreenController.changeBackgroundView(CallScreenController.java:578)
       at com.vyng.dialer_ui.call_screen.CallScreenPresenter.onViewAttach(CallScreenPresenter.java:93)
       at com.vyng.dialer_ui.call_screen.CallScreenController.onAttach(CallScreenController.java:168)
       at com.bluelinelabs.conductor.Controller$7.run(Controller.java:843)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6565)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by EricKuck** [comment]
Without some sample code it's hard to say what's going on. You are correct though that views are available in `onAttach`.
