### ISSUE TITLE
performDestroy: Null arg being passed to NonNull parameter

### ISSUE THREAD

**Issue by tomblenz** [bluelinelabs/Conductor#516]
Controller.performDestroy() notifies its lifecycle listeners as follows
```
lifecycleListener.preContextUnavailable(this, getActivity());
```
However, getActivity() is `@Nullable `
```
@Nullable public final Activity getActivity() { ... }
```
and LifecycleListener's preContextUnavailable is `@NonNull`:
```
public static abstract class LifecycleListener {
   ...
   public void preContextUnavailable(@NonNull Controller controller, @NonNull Context context) { }
   ...
}
```

In terms of real-world impact, it turns out getActivity() *can* be null in this case, which produces a crash in a Kotlin class which extends LifecycleListener as Kotlin is more strict about what arguments are actually passed.
```
java.lang.RuntimeException: Unable to destroy activity {myactivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4383)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
    at android.app.ActivityThread.-wrap5(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context
    at com.mylib.lifecycle.ControllerLifecycleOwner$1.preContextUnavailable(Unknown Source:7)
    at com.bluelinelabs.conductor.Controller.performDestroy(Controller.java:1074)
    at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:996)
    at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1121)
    at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1106)
    at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:61)
    at com.bluelinelabs.conductor.Backstack.popAll(Backstack.java:78)
    at com.bluelinelabs.conductor.Router.destroy(Router.java:223)
    at com.bluelinelabs.conductor.ControllerHostedRouter.destroy(ControllerHostedRouter.java:89)
    at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1117)
    at com.bluelinelabs.conductor.Controller.activityDestroyed(Controller.java:865)
    at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:599)
    at com.bluelinelabs.conductor.ActivityHostedRouter.onActivityDestroyed(ActivityHostedRouter.java:61)
    at com.bluelinelabs.conductor.internal.LifecycleHandler.destroyRouters(LifecycleHandler.java:210)
    at com.bluelinelabs.conductor.internal.LifecycleHandler.onDestroy(LifecycleHandler.java:161)
    at android.app.Fragment.performDestroy(Fragment.java:2768)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1432)
    at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
    at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
    at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3007)
    at android.app.FragmentController.dispatchDestroy(FragmentController.java:244)
    at android.app.Activity.performDestroy(Activity.java:7244)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250)
```

**Comment by tomblenz** [comment]
p.s. workaround for anyone with this issue is to [create an interim listener in Java](https://stackoverflow.com/questions/36343280/how-can-i-override-a-java-method-and-change-the-nullability-of-a-parameter) which removes the `@NonNull` annotation.

**Comment by morder** [comment]
approved, reproducible in 3.0.0-rc2 and 2.1.5 versions
