### ISSUE TITLE
NullPointerException with unregisterForActivityResults

### ISSUE THREAD

**Issue by sklinefelter** [bluelinelabs/Conductor#567]
I am using the 3.0.0-rc2 version of conductor and seeing this crash occasionally when popping a current controller:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.LifecycleHandler.unregisterForActivityResults(java.lang.String)' on a null object reference
at com.bluelinelabs.conductor.ActivityHostedRouter.unregisterForActivityResults(ActivityHostedRouter.java:105)
at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1114)
at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1107)
at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:61)
at com.bluelinelabs.conductor.Router.popController(Router.java:137)
at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:120)
```

I've reviewed a few of the previous issues and they are marked as closed from the 2.x version.

Any suggestions or direction here?

**Comment by ihrupin** [comment]
I'm reproducing the issue with the same stacktrace.

**Comment by soniccat** [comment]
Mmm, if an ActivityHostedRouter.lifecycleHandler is null then you call this at the moment when your activity is already destroyed. I'd consider checking Activity.isFinishing before calling popCurrentController.

**Comment by sklinefelter** [comment]
Any update or movement on this?  Still experiencing this crash.

**Comment by PaulWoitaschek** [comment]
This is my top crash with 3.0.0-rc06 right now.

Here is a complete stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluelinelabs.conductor.internal.LifecycleHandler.a(java.lang.String)' on a null object reference
       at com.bluelinelabs.conductor.ActivityHostedRouter.unregisterForActivityResults(ActivityHostedRouter.java:105)
       at com.bluelinelabs.conductor.ControllerHostedRouter.unregisterForActivityResults(ControllerHostedRouter.java:190)
       at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1128)
       at com.bluelinelabs.conductor.Controller.destroy(Controller.java:1121)
       at com.bluelinelabs.conductor.Backstack.pop(Backstack.java:62)
       at com.bluelinelabs.conductor.Backstack.popAll(Backstack.java:79)
       at com.bluelinelabs.conductor.Router.destroy(Router.java:224)
       at com.bluelinelabs.conductor.ControllerHostedRouter.destroy(ControllerHostedRouter.java:90)
       at com.bluelinelabs.conductor.Controller.removeChildRouter(Controller.java:254)
       at com.bluelinelabs.conductor.viewpager.RouterPagerAdapter.destroyItem(RouterPagerAdapter.java:118)
       at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:511)
       at com.yazio.android.diary.DiaryController.onDestroyBinding(DiaryController.java:131)
       at com.yazio.android.diary.DiaryController.onDestroyBinding(DiaryController.java:21)
       at com.yazio.android.sharedui.conductor.ViewBindingController.onDestroyView(ViewBindingController.java:47)
       at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:988)
       at com.bluelinelabs.conductor.Controller.detach(Controller.java:973)
       at com.bluelinelabs.conductor.Controller$1.onDetached(Controller.java:1053)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportDetached(ViewAttachHandler.java:100)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.onViewDetachedFromWindow(ViewAttachHandler.java:55)
       at android.view.View.dispatchDetachedFromWindow(View.java:15558)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3236)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3228)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3406)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6117)
       at android.view.ViewRootImpl.die(ViewRootImpl.java:6094)
       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4533)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4785)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

in onDestroyView I'm nulling a pager adapter which is a RouterPagerAdapter.
