### ISSUE TITLE
targetConroller is null

### ISSUE THREAD

**Issue by TikTak123** [bluelinelabs/Conductor#597]
**Conductor version:**
implementation 'com.bluelinelabs:conductor:3.0.0-rc2'

**API level:**
Android 5, 6, 7, 8, 9,10

**Error log:**
```
Fatal Exception: kotlin.TypeCastException: null cannot be cast to non-null type com.example.ui.multiAccount.MultiAccountControllerTargetCallback
       at com.example.ui.multiAccount.MultiAccountController.onDestroy(MultiAccountController.java:46)
       at com.bluelinelabs.conductor.Controller.performDestroy(Controller.java:1095)
       at com.bluelinelabs.conductor.Controller.removeViewReference(Controller.java:997)
       at com.bluelinelabs.conductor.Controller.detach(Controller.java:960)
       at com.bluelinelabs.conductor.Controller$7.onDetached(Controller.java:1039)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportDetached(ViewAttachHandler.java:103)
       at com.bluelinelabs.conductor.internal.ViewAttachHandler.onViewDetachedFromWindow(ViewAttachHandler.java:58)
       at android.view.View.dispatchDetachedFromWindow(View.java:17541)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3703)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5247)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5218)
       at android.view.ViewGroup.removeView(ViewGroup.java:5149)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$1.onAnimationEnd(AnimatorChangeHandler.java:200)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
       at android.animation.AnimatorSet.end(AnimatorSet.java:515)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.completeImmediately(AnimatorChangeHandler.java:87)
       at com.bluelinelabs.conductor.ControllerChangeHandler.abortOrComplete(ControllerChangeHandler.java:146)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:173)
       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:823)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:793)
       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:775)
       at com.bluelinelabs.conductor.Router.popController(Router.java:138)
       at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:120)
       at com.bluelinelabs.conductor.Router.handleBack(Router.java:98)
       at com.example.MainActivity.onBackPressed(MainActivity.java:288)
       at android.app.Activity.onKeyUp(Activity.java:3035)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2732)
       at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:357)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4832)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4704)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4239)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4385)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4266)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4442)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4239)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4266)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4239)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4418)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4586)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2444)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2007)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1998)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2421)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:331)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:6635)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Sample code:**
This is how I call controller
```
@Override
    public void gotoMultiAccount() {
        MultiAccountController controller = new MultiAccountController();
        controller.setMultiAccountControllerListener(this);

        getTopRouter().pushController(RouterTransaction.with(controller)
                .pushChangeHandler(new FadeChangeHandler(false))
                .popChangeHandler(new FadeChangeHandler()));
    }
```

```
class MultiAccountController : BaseController(), MultiAccountCallback {

    @Inject
    lateinit var mViewModel: MultiAccountViewModel
    lateinit var binding: ControllerMultiAccountBinding

    fun <T> setMultiAccountControllerListener(targetController: T) where T : Controller, T : MultiAccountControllerTargetCallback {
        setTargetController(targetController)
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
        BaseApplication.getComponent().controllerComponent(ControllerModule(activity)).inject(this)
        binding = ControllerMultiAccountBinding.inflate(inflater, container, false)
        binding.viewmodel = mViewModel
        mViewModel.setCallback(this, args)

        binding.swipeLayout.setColorSchemeResources(R.color.colorPrimary, R.color.black)
        activity?.window?.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)

        return binding.root
    }

    override fun onDestroy() {
        (targetController as MultiAccountControllerTargetCallback).onMultiAccountControllerDismiss()
        activity?.window?.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)
        super.onDestroy()
    }

    override fun bindAccounts(adapter: AccountAdapter) {
        binding.rvAccounts.layoutManager = LinearLayoutManager(activity)
        binding.rvAccounts.adapter = adapter
    }

    override fun bindEditorActionListener(listener: TextView.OnEditorActionListener) {
        binding.etPhoneNumber.setOnEditorActionListener(listener)
    }

    override fun openPersonalSettings() {
        router.replaceTopController(
            RouterTransaction.with(
                    PersonalSettingsController()
                )
                .pushChangeHandler(FadeChangeHandler())
                .popChangeHandler(FadeChangeHandler())
        )
    }

    override fun showAddPhoneDialog(phone: String) {
        router.popCurrentController()
        (targetController as MultiAccountControllerTargetCallback).onMultiAccountControllerAddPhoneClick(
            phone
        )
    }

    override fun showMultiAccountSmsDialog(name: String, phone: String) {
        router.popCurrentController()
        (targetController as MultiAccountControllerTargetCallback).onMultiAccountControllerShowSmsDialogClick(
            name,
            phone
        )
    }

    override fun closeController() {
        router.popCurrentController()
    }

    override fun onChangeStarted(
        changeHandler: ControllerChangeHandler,
        changeType: ControllerChangeType
    ) {
        super.onChangeStarted(changeHandler, changeType)
        if (!changeType.isEnter) {
            mViewModel.onDetach()
        } else {
            binding.root.postDelayed({
                mTabStateManager.setTab(TabStateManager.Tabs.MULTI_ACCOUNT_SCREEN)
                mViewModel.onAttach()
            }, 30)
        }
    }

    override fun showMessage(message: String, vararg duration: Int) {
        showToast(binding.root, message)
    }

    override fun showMessage(message: Int, vararg duration: Int) {
        showToast(binding.root, message)
    }
}
```

```
@PerController
class MultiAccountViewModel @Inject constructor() : BaseViewModel<MultiAccountCallback>() {

    @Inject
    lateinit var mAccountAdapter: AccountAdapter
    private lateinit var editorActionListener: TextView.OnEditorActionListener
    var allUsers: AllUsersResponse? = null
    var shouldShowAddPhoneBlock = ObservableBoolean()

    override fun init(args: Bundle) {

        mAccountAdapter.listener = BaseViewHolder.ClickListener { item ->
            when (item) {
                is SubUser -> {
                    mPreferencesHelper.subAccount = item.subAccount
                    mRepository.invalidateOffersCache()
                    mRepository.invalidateDashboardCache()
                    mRepository.invalidateMultiAccountCache()
                    mRepository.invalidateQuizCache()
                    mRepository.invalidateClubCache()
                    mCallback.closeController()
                }
                is Await -> {
                    mCallback.showMultiAccountSmsDialog(item.name!!, item.account)
                }
            }
        }

        editorActionListener = TextView.OnEditorActionListener { v, actionId, event ->
            if (actionId == EditorInfo.IME_ACTION_DONE) {
                mCallback.showAddPhoneDialog((v as MaskedEditTextExtend).rawText)
                true
            }

            false
        }

        mCallback.bindAccounts(mAccountAdapter)
        mCallback.bindEditorActionListener(editorActionListener)
    }

    override fun onAttach() {
        super.onAttach()
        loadAllMultiAccountUsers(false)
    }

    @SuppressLint("CheckResult")
    fun loadAllMultiAccountUsers(getNewData: Boolean) {
        mRepository.getMultiAccountAllUsers(
                mPreferencesHelper.myPhoneNumber,
                mPreferencesHelper.subAccount,
                getNewData
            )
            .compose(RxUtil.applyDefaults(this))
            .subscribe({ response ->
                allUsers = response
                handleResponse(response.subUsers)
                loadSubUsersBalance(false)
            }, {
                handleError(it)
            })
    }

    @SuppressLint("CheckResult")
    fun onUpdateBalancesClick() {
        loadSubUsersBalance(true)
    }

    @SuppressLint("CheckResult")
    private fun loadSubUsersBalance(getNewData: Boolean) {
        mRepository.getSubUsersBalance(mPreferencesHelper.myPhoneNumber, getNewData)
            .compose(RxUtil.applyDefaults(this))
            .subscribe({
                handleResponse(it)
            }, {
                handleError(it)
            })
    }

    private fun handleResponse(subUsers: List<SubUser>) {
        val subAccount = mPreferencesHelper.subAccount

        if (subUsers.isEmpty()) return

        if (subUsers.size + (allUsers?.awaitingWrappers?.size ?: 0) > 1)
            shouldShowAddPhoneBlock.set(false)
        else
            shouldShowAddPhoneBlock.set(true)

        subUsers[0].name = mContext.getString(R.string.multi_account_my_number)
        mAccountAdapter.items.clear()
        mAccountAdapter.items.addAll(subUsers)
        mAccountAdapter.items.addAll(allUsers?.awaitingWrappers ?: emptyList())

        for ((index, value) in mAccountAdapter.items.withIndex()) {
            if (value is SubUser && value.subAccount == subAccount) {
                mAccountAdapter.selectedPosition = index
                break
            }
        }

        mAccountAdapter.notifyDataSetChanged()
    }

    fun onAddPhoneNumberClick(phone: String) {
        mCallback.showAddPhoneDialog(phone)
    }

    fun onPersonalSettingsClick() {
        mCallback.openPersonalSettings()
    }

    fun onCloseClick() {
        mCallback.closeController()
    }
}
```

```
interface MultiAccountControllerTargetCallback {
    fun onMultiAccountControllerAddPhoneClick(phone: String)
    fun onMultiAccountControllerShowSmsDialogClick(name: String, phone: String)
    fun onMultiAccountControllerDismiss()
}
```

I have another Controller which is like in this example and targetController is null in onDestroy method

**Comment by TikTak123** [comment]
I tried to reproduce this crash. I killed app process. Then restore them. Only after that crash occures. How can I solve this crash?

**Comment by EricKuck** [comment]
I unfortunately haven't been able to reproduce this, even after killing the process. Could you maybe create a sample application that makes it reproducible for me? I'd love to fix this if possible.

**Comment by TikTak123** [comment]
Of course I will try to write some sample project where this error reproduce. But I’m busy now. I have own tasks in project. When I will be free, of course I will try to write sample project. Thank you.

**Comment by TikTak123** [comment]
Here is sample project
https://github.com/TikTak123/SampleConductorProject

**Comment by EricKuck** [comment]
The reason it fails in your demo is because `FirstController` has this logic in `onCreateView`:

```
val childRouter = getChildRouter(container)
childRouter.setRoot(RouterTransaction.with(SecondController()))
```

This means you're replacing the `SecondController` instance that was already there when the view is created, which destroys the target relationship `AlertController` had. Replace this logic with this and it will all work correctly:

```
val childRouter = getChildRouter(container)
if (!childRouter.hasRootController()) {
  childRouter.setRoot(RouterTransaction.with(SecondController()))
}
```

**Comment by TikTak123** [comment]
Thank you this helped to me
