### ISSUE TITLE
IncompatibleClassChangeError with 3.0.0-rc5

### ISSUE THREAD

**Issue by ragaisis** [bluelinelabs/Conductor#609]
I have code like this 

    private fun setupNavigationDrawer(savedInstanceState: Bundle?) {
        val menuContainer = findViewById<FrameLayout>(R.id.view_drawer_container)
        menuRouter = Conductor.attachRouter(this, menuContainer, savedInstanceState)
        if (!menuRouter!!.hasRootController()) {
            val menuController = Class.forName("com.my.app.ui.menu.MenuScreen")
            menuRouter?.setRoot(RouterTransaction.with(menuController.newInstance() as Controller))
        }
    }

that worked with 

    api 'com.bluelinelabs:conductor:3.0.0-rc1'
    api 'com.bluelinelabs:conductor-archlifecycle:3.0.0-rc1'
    api 'com.bluelinelabs:conductor-support:3.0.0-rc1'

It works well with 3.0.0-rc3 that is last compatible version. But after switching to 

    api 'com.bluelinelabs:conductor:3.0.0-rc5'
    api 'com.bluelinelabs:conductor-archlifecycle:3.0.0-rc5'
    api 'com.bluelinelabs:conductor-viewpager:3.0.0-rc5'

and some refactoring due to breaking changes. e.g. 

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup): View {
        super.onCreateView(inflater, container)

should be changed to with adding  `savedViewState: Bundle?`

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup,
        savedViewState: Bundle?
    ): View {
        super.onCreateView(inflater, container, savedViewState)

and also this was required code change and might be the the case why build is failing

        controller.addLifecycleListener(object : Controller.LifecycleListener() {
to

        controller.addLifecycleListener(object : Controller.LifecycleListener {

I got exception while starting the app

2020-05-22 03:32:32.994 19314-19314/com.my.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app.debug, PID: 19314
    java.lang.IncompatibleClassChangeError: Superclass com.bluelinelabs.conductor.Controller$LifecycleListener of com.hannesdorfmann.mosby3.mvp.conductor.delegate.MvpConductorLifecycleListener is an interface (declaration of 'com.hannesdorfmann.mosby3.mvp.conductor.delegate.MvpConductorLifecycleListener' appears in /data/app/com.my.app.debug-MJECPqk2ZYn2Ua8onHDHiw==/base.apk)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.my.app.ui.MainActivity.setupNavigationDrawer(MainActivity.kt:213)
        at com.my.app.ui.MainActivity.onCreate(MainActivity.kt:140)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by EricKuck** [comment]
This error is coming from mosby, which is built with Conductor 2 in mind. The only way this issue will be resolved is if/when mosby updates to Conductor 3. This is unlikely to happen until 3.0 is actually released.
