### ISSUE TITLE
AbstractMethodError preContextAvailable(com.bluelinelabs.conductor.Controller) on API 23 

### ISSUE THREAD

**Issue by levthn** [bluelinelabs/Conductor#623]
Conductor version 3.0.1-SNAPSHOT

```
 Caused by: java.lang.AbstractMethodError: abstract method "void com.bluelinelabs.conductor.Controller$LifecycleListener.preContextAvailable(com.bluelinelabs.conductor.Controller)"
        at com.bluelinelabs.conductor.Controller.onContextAvailable(Controller.java:809)
        at com.bluelinelabs.conductor.Router.setControllerRouter(Router.java:968)
        at com.bluelinelabs.conductor.Router.setBackstack(Router.java:437)
        at com.bluelinelabs.conductor.Router.setRoot(Router.java:337)
```

**Comment by EricKuck** [comment]
This has been fixed in 8575f534366a26230744ce98f6970f2a9e600fbc. I'm not sure what was causing it, but it was something with Java 8. We'll be moving more towards kotlin soon anyway, so this change wasn't needed.
