### ISSUE TITLE
popCurrentController ConcurrentException

### ISSUE THREAD

**Issue by leonardo2204** [bluelinelabs/Conductor#63]
My scenario is:
I have 2 Controllers, a list and add button that goes to another Controller (edit or new). The second controller has a Toolbar with a back button (actionBar.setDisplayHomeAsUpEnabled(true)).
My callback:
```
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                getRouter().popCurrentController();
            default:
                return super.onOptionsItemSelected(item);
        }
    }
```
The add button (1st Controller):
`getRouter().pushController(RouterTransaction.builder(new KidsRegisterController(false, null, this)).build());`

The problem is, after the second open and go back (From 1st -> 2nd and then back for the second time)
the second Controller is never popped, and if I click the back button I get this exception:

> FATAL EXCEPTION: main
>                                                                java.lang.RuntimeException: Unable to destroy activity {br.com.dinda.qa/br.com.dinda.views.activities.KidsActivity}: java.util.ConcurrentModificationException
>                                                                    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3273)
>                                                                    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291)
>                                                                    at android.app.ActivityThread.access$1200(ActivityThread.java:130)
>                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
>                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                    at android.os.Looper.loop(Looper.java:137)
>                                                                    at android.app.ActivityThread.main(ActivityThread.java:4745)
>                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
>                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
>                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>                                                                    at dalvik.system.NativeStart.main(Native Method)
>                                                                 Caused by: java.util.ConcurrentModificationException
>                                                                    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
>                                                                    at com.bluelinelabs.conductor.Router.onActivityDestroyed(Router.java:392)
>                                                                    at com.bluelinelabs.conductor.internal.LifecycleHandler.onDestroy(LifecycleHandler.java:123)
>                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
>                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
>                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
>                                                                    at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1826)
>                                                                    at android.app.Activity.performDestroy(Activity.java:5171)
>                                                                    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
>                                                                    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3260)
>                                                                    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291) 
>                                                                    at android.app.ActivityThread.access$1200(ActivityThread.java:130) 
>                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248) 
>                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
>                                                                    at android.os.Looper.loop(Looper.java:137) 
>                                                                    at android.app.ActivityThread.main(ActivityThread.java:4745) 
>                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                    at java.lang.reflect.Method.invoke(Method.java:511) 
>                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
>                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
>                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by leonardo2204** [comment]
My fault, I forgot the return, sorry for bothering.
