### ISSUE TITLE
Proguard / R8 rules for default constructors

### ISSUE THREAD

**Issue by tomblenz** [bluelinelabs/Conductor#639]
I've noticed an issue around R8 removing default constructors for change handlers.
```
Fatal Exception: java.lang.RuntimeException: class my.app.ui.c.l.b does not have a default constructor.
       at com.bluelinelabs.conductor.ControllerChangeHandler.ensureDefaultConstructor(ControllerChangeHandler.java:113)
       at com.bluelinelabs.conductor.ControllerChangeHandler.<init>(ControllerChangeHandler.java:44)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.<init>(AnimatorChangeHandler.java:50)
       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.<init>(AnimatorChangeHandler.java:42)
       at my.app.changehandler.PopupChangeHandler.<init>(PopupChangeHandler.java:21)
       ...
```

The following rules appear to address this

```
-keepclassmembers public class * extends com.bluelinelabs.conductor.Controller {
   public <init>();
   public <init>(android.os.Bundle);
}
-keepclassmembers public class * extends com.bluelinelabs.conductor.ControllerChangeHandler {
    public <init>(...);
}
```

**Comment by EricKuck** [comment]
Thanks for bringing this up. It has been addressed in 9ce27e4deeec69c53f6cbb674590da47aa2a1571
