### ISSUE TITLE
[Demo] Child Controllers screen crash on orientation change

### ISSUE THREAD

**Issue by adi1133** [bluelinelabs/Conductor#95]
This crash happens if the activity changes orientation while it is loading and animating its child views.

```
07-15 12:14:12.200 1377-1377/com.bluelinelabs.conductor.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.bluelinelabs.conductor.demo, PID: 1377
                                                                               Theme: themes:{}
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bluelinelabs.conductor.demo/com.bluelinelabs.conductor.demo.MainActivity}: java.util.ConcurrentModificationException
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4111)
                                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                Caused by: java.util.ConcurrentModificationException
                                                                                   at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                   at com.bluelinelabs.conductor.Controller.restoreViewState(Controller.java:908)
                                                                                   at com.bluelinelabs.conductor.Controller.inflate(Controller.java:816)
                                                                                   at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:124)
                                                                                   at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:566)
                                                                                   at com.bluelinelabs.conductor.Router.rebindIfNeeded(Router.java:358)
                                                                                   at com.bluelinelabs.conductor.Conductor.attachRouter(Conductor.java:33)
                                                                                   at com.bluelinelabs.conductor.demo.MainActivity.onCreate(MainActivity.java:34)
                                                                                   at android.app.Activity.performCreate(Activity.java:6251)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                                   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4111) 
                                                                                   at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by EricKuck** [comment]
I've tried to reproduce this a few different ways and can't seem to do it. Maybe it's a timing thing? Do you have any tips on getting it to happen?

**Comment by adi1133** [comment]
The issue is still happening on 9f64038 .
To reproduce, rotate the screen immediately after pressing the Child Controllers button.
I just tested on a OnePlus One running android 6.0.1 (CM13)
